var metricWrapper = document.createElement("div");
metricWrapper.className = "metric-wrapper";
document.getElementsByClassName("main-wrapper")[0].appendChild(metricWrapper);
var btn = document.createElement("button");
btn.innerHTML = "COINS COLLECTED";
var btn2 = document.createElement("button");
btn2.innerHTML = "DISTANCE FROM START";
var btn3 = document.createElement("button");
btn3.innerHTML = "ENEMIES KILLED";
document.getElementsByClassName("metric-wrapper")[0].appendChild(btn);
document.getElementsByClassName("metric-wrapper")[0].appendChild(btn2);
document.getElementsByClassName("metric-wrapper")[0].appendChild(btn3);
